package bimock

import (
	"net/http"
	"fmt"
	"github.com/sirupsen/logrus"
	"encoding/json"
)

type sensorData struct {
	RideID string
	Lat float64
	Lon float64
}

func readData(r *http.Request, s *Server, rideID string) {
	// TODO
	fmt.Println("reading")
	decoder := json.NewDecoder(r.Body)
	var data sensorData
	err := decoder.Decode(&data)
	if err != nil {
		logrus.WithError(err).Fatal("Failed to parse JSON")
	}
	fmt.Println(data)
	//TODO: Use this data generated by simulator to store in database or do some operation
}
